### ISSUE TITLE
[DEV] After entering 'Statystyki' page, error is visible

### ISSUE THREAD

**Issue by Quer1234** [DevAdventCalendar/DevAdventCalendar#467]
1. Login as a user
2. Do not answer for any available question
3. Go to the page : https://dev.devadventcalendar.pl/Manage/DisplayStatistics

Actual Results:

An unhandled exception occurred while processing the request.
InvalidOperationException: Sequence contains no elements.
lambda_method(Closure , QueryContext , DbDataReader , ResultContext , int[] , ResultCoordinator )

System.InvalidOperationException: Sequence contains no elements.
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Max[TSource,TResult](IQueryable`1 source, Expression`1 selector)
   at DevAdventCalendarCompetition.Repository.StatisticsRepository.GetAnsweredCorrectMaxTestId(String userId) in /app/DevAdventCalendarCompetition.Repository/StatisticsRepository.cs:line 44
   at DevAdventCalendarCompetition.Services.StatisticsService.GetHighestTestNumber(String userId) in /app/DevAdventCalendarCompetition.Services/StatisticsService.cs:line 43
   at DevAdventCalendarCompetition.Services.StatisticsService.FillResultsWithTestStats(String userId) in /app/DevAdventCalendarCompetition.Services/StatisticsService.cs:line 22
   at DevAdventCalendarCompetition.Controllers.ManageController.DisplayStatistics() in /app/DevAdventCalendarCompetition/Controllers/ManageController.cs:line 368
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.HttpMethodOverrideMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Mejtika** [comment]
I checked it several times but I was unable to reproduce the bug. I've added some screenshots from my configuration.

![image](https://user-images.githubusercontent.com/28907927/100445281-21d4c600-30ad-11eb-823f-76a124ea7f15.png)
![image](https://user-images.githubusercontent.com/28907927/100445294-26997a00-30ad-11eb-8c1a-35d7d2a90acd.png)
![image](https://user-images.githubusercontent.com/28907927/100445298-28633d80-30ad-11eb-9069-5f22e4806f0f.png)

**Comment by Quer1234** [comment]
Checking now, and also cannot reproduce.

**Comment by WTobor** [comment]
ok, so @BlackMorzan please check where is _Single()_ and replace it with _SingleOrDefault()_ and null check

**Comment by BlackMorzan** [comment]
I also can not reproduce this behaviour and it seems that I didn't use any Single() method in StatisticsRepository. 

This is the line that might cause the problem. 
`
            return this._dbContext.UserTestCorrectAnswers.Any()
                ? this._dbContext
                .UserTestCorrectAnswers
                .Where(a => a.UserId == userId)
                .Max(a => a.TestId)
                : 0;
`
For me it looks alright although maybe someone else coud see what I did wrong.

**Comment by WTobor** [comment]
it looks ok
probably the problem can be also here
![image](https://user-images.githubusercontent.com/22730914/100545847-589e0e00-325e-11eb-806f-8dca811e28ae.png)
before Max() we need to check if the sequence contains elements

**Comment by BlackMorzan** [comment]
Agree. This is why I used ...UserTestsWrongAnswers.Any()

**Comment by WTobor** [comment]
but you don't check UserTestsWrongAnswers.Where(a => a.UserId == userId).Any() (and the same with UserTesstCorrectAnswers) :)

**Comment by BlackMorzan** [comment]
Yes - that makes sense! I'm creating a pull-request
